### ISSUE TITLE
APIの実装

### ISSUE THREAD

**Issue by trileg** [kanarne/busnoyatsu#1]
Slackのbotなどで簡単にデータを取得できるようなAPIを実装してほしい．

**Comment by trileg** [comment]
APIの実装に興味があるので，実装してみてもいいですか？
`/api/v1/next-bus/to-takatsuki`みたいなURLでGETを送ると，次のバス時刻に関するデータをJSONで返すような感じの実装を考えてます．

**Comment by kanarne** [comment]
@trileg 実装するならそういう形だと僕も考えてました．お願いします．
